name: Upload Python Package

on:
  # Ручной запуск из интерфейса GitHub
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия для релиза (например, v0.1.0)'
        required: true
        default: 'v0.1.0'
      create_release:
        description: 'Создать релиз на GitHub'
        required: true
        type: boolean
        default: true

permissions:
  contents: write # Нужно для создания релиза

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Update version in pyproject.toml
        if: ${{ github.event.inputs.version != '' }}
        run: |
          # Получаем версию без префикса 'v'
          VERSION=$(echo "${{ github.event.inputs.version }}" | sed 's/^v//')
          sed -i "s/version = \"[^\"]*\"/version = \"$VERSION\"/" pyproject.toml

      - name: Check project files
        run: ls -la

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
          
      - name: Create Release
        if: ${{ github.event.inputs.create_release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          generate_release_notes: true
          files: |
            dist/*

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/moy-nalog-py

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
